volumes:
  service_data:
    driver: local
  
services :
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  admin:
    image: adminer
    restart: always
    depends_on:
    - db
    ports:
    - 9080:8080